[package]
name = "ra4m2-hal"
version = "0.1.0"
edition = "2024"

[dependencies]
ra4m2-pac = { git = "https://github.com/amcelroy/ra-pac", features = ["all", "rt"] }
cortex-m = { version = "0.7", features = [ "critical-section-single-core",], default-features = false }
cortex-m-rt = { version = "0.7" }
defmt = "1.0.1"
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy.git", rev = "68c8238", optional = true }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "68c8238" }

[features]
default = ["embassy_time"]

embassy_time = ["dep:embassy-time-driver", "agt0"]

agt0 = []